#ifndef CDLGDEFINE_H
#define CDLGDEFINE_H
#include <QSize>
const int GAP = 5;
const int XCORD = 20;
const int YCORD = 20;
const int DEFAULT_HEIGHT = 28;
const int DEFAULT_WIDTH = 65;
const QSize BUTTON_SIZE = QSize(DEFAULT_WIDTH, DEFAULT_HEIGHT);
const QSize DATE_SIZE = QSize((2*DEFAULT_WIDTH), DEFAULT_HEIGHT);
const QSize DEPT_ACCOUNT_COMBO_SIZE = QSize((4*DEFAULT_WIDTH), DEFAULT_HEIGHT);

#endif // CDLGDEFINE_H
