#ifndef CSDDEFINE_H
#define CSDDEFINE_H

#define NEW_TRANSACTION_SIGNAL 1
#define ASSIGN_RECEIPT_SIGNAK  2
#define IMPORT_BANK_STATEMENT  3
#define REMITTANCE_SIGNAL 4
#define PROCESS_BANK_STATEMENT 5
#define SUMMARY_SIGNAL 6
#define SEND_SMS_SIGNAL 7

#endif // CSDDEFINE_H
